version: '3.8'

services:
  personal-finance-api:
    build: .
    container_name: personal-finance-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - DEFAULT_CURRENCY=ARS
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future: Add database service when migrating from in-memory storage
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: personal-finance-db
  #   environment:
  #     POSTGRES_DB: personal_finance
  #     POSTGRES_USER: finance_user
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data: